# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Eryn &hearts; Riley
tagline:             '#stronglove'
url:                 http://www.erynandriley.com
baseurl:             /
paginate:            5
paginate_path:       "/posts/page:num/"

# About/contact
author:
  name: Riley Strong
  email: eponymous@rileystrong.com

date: 2015-10-03
